[build-system]
requires = [
    "setuptools>=82.0.1",
    "wheel>=0.48.0",
    "setuptools_scm>=10.2.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"
write_to = "volkswagencarnet/version.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
asyncio_mode = "strict"
testpaths = ["tests"]
python_files = ["*_test.py"]
